package com.community.model;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated Sun Jun 21 22:06:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.name
     *
     * @mbg.generated Sun Jun 21 22:06:13 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated Sun Jun 21 22:06:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated Sun Jun 21 22:06:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.name
     *
     * @return the value of topic.name
     *
     * @mbg.generated Sun Jun 21 22:06:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.name
     *
     * @param name the value for topic.name
     *
     * @mbg.generated Sun Jun 21 22:06:13 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}